language: en
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

pipeline:
  - name: WhitespaceTokenizer
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: DIETClassifier
    epochs : 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    epochs: 100
  - name: MappingPolicy
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.001
    core_threshold: 0.001
    fallback_action_name: "utter_fallback"